### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by chrisbog94** [oxguy3/coebot-www#1]
Very nice bot, website seems to be going in the right direction.

Only gripe with this repo, is the lack of a .sql file for the database connect.

Please add this? :D

EDIT:
I'm pretty handy, but some of your code is confusing.
Would like a complete installation guide.

**Comment by hayleox** [comment]
I would, but it's still in pretty early development and the database is
changing all the time. I could add an SQL file but itd probably be outdated
in a week. Once the site is sorta at a v1.0, I'll focus more on making this
repo easy to fork.

**Comment by chrisbog94** [comment]
Anyways, Thanks for your hard work. Nice website design!

**Comment by hayleox** [comment]
Thanks man!

**Comment by Yub0** [comment]
Up? :cry:

**Comment by hayleox** [comment]
Hey sorry, never updated this ticket. The database structure is in the file dbstructure.sql.
